### ISSUE TITLE
tables with __call metamethods should be memoizable

### ISSUE THREAD

**Issue by kikito** [kikito/memoize.lua#2]
Not only that: if their __call metamethod changes, memoize should "intelligently" discard the old memoizations.

Edge cases:
When `memoized_f = memoize(f)`
- `memoize(f)` should throw an error if f is a table and it doesn't have a __call metamethod.
- `memoized_f(...)` should throw en error if f doesn't have a __call method any more.

**Comment by Uzume** [comment]
It should be noted that callable objects with `__call` metamethods **CANNOT** be used as a `__call` metamethod for another object. This means that the value of a `__call` key **MUST** be a lua or C function and not another callable object like a callable table object. One can set table `__call` key values to things other than functions but attempting call objects with such a metatable will fail.

It should probably also be noted that other types besides tables can be callable objects. For example, all strings already have a metatable with its `__index` set to the `string` table so one can do things like `local s = [[ABC]]; print(s:byte(1, s:len()))`. However this also means it is easy to make strings callable via code like:
```
-- All strings share a single metatable so this makes all strings callable
getmetatable(_VERSION).__call = function(self, ...)
  return self:byte(1, self:len())
end
print(([[ABC]])())
```

I noticed the code here tests for the wrong conditions and the tests also do not have appropriate test cases for these situations.
