### ISSUE TITLE
Feature request: dememoize

### ISSUE THREAD

**Issue by tw-bert** [kikito/memoize.lua#5]
Your module works great.

Our usecase is a bit special: we use it inside Redis. Scripts are run inside the Redis engine. Sidenote: within Redis, trying to write to the global environment is forbidden (and blocked for _G).

Your comment:
> This function does not use weak tables for caching; the memory devoted to memoizing is thus not-recuperable  

is spot-on, and can indeed be repro'd in a dev environment.

If I have a local function, and use memoize on it, I have a mem leak. The parms-cache is cleared by calling memoize() again at the end of our Lua script, but each time the Lua script is evaluated, the local function is a newly created instance of that function, and gets collected by your memoize function (which *is* global in our redis environment _- ... allowed from a redis point of view, because we enforce script effects replication -_ ).
We do have a simple workaround: make our functions semi-global, by putting them in an existing global dict, and reuse them.

However, this workaround is error prone, and does not play nicely with rarely used functions. Redis can be running for months, and it would be nice to have a way of unmemoizing functions (and removing the dict entry to the function pointer inside your memoize lib). This approach does not require weak refs (which have their own downsides).

_P.S._ We do have another workaround: replace your module by a new instance (on a running redis server), and the alloced 'mem-leak' will be freed again.

**Comment by kikito** [comment]
Right now there's a way to dememoize functions, which is calling memoize on the original function again. I'm just pointing this out in case you have missed it.

If I did this module today I would do it in a different way: every memoized function would come with its own cache (via an upvalue) and there would be no "module-level" cache. That way the memory used by a memoized function `m` would stop being used when `m` stops being used (when it is not referenced any more, and the garbage collector has been run once or twice).

Would this solution be good enough for you? I have little availability these days so it might take me a while before I am able to implement this.

**Comment by tw-bert** [comment]
Your new design would solve our issue. 
It would be a big help, and doesn't matter if it takes a while (we have workarounds).

**Comment by kikito** [comment]
Hi, please try this version: https://github.com/kikito/memoize.lua/blob/cache-per-function/memoize.lua

It should work as I described above. I am not releasing a new version just now because I need to do some secondary stuff (update docs, create a rockspec) before.

**Comment by tw-bert** [comment]
Brilliant, I'll test next Monday

**Comment by kikito** [comment]
I have released memoize.lua v2.0 (and removed the branch I linked above). Please try the version in the master branch. I've updated the docs as well. If it covers all your needs, please come back and close this issue, thanks!

**Comment by tw-bert** [comment]
Thank you, I've upgraded to 2.0 and it seems to be working perfectly.
One last doublecheck, if you'd like to think along:

I expect the following scenarios not to have memleaks (no dangling pointers, all refs decreased to 0):
1. After redis-evaluating a loose Lua script, when I memoize a __global__ function (the redis-lua equivalent, for example using the `math` module dict, but we do it slightly less ugly) like this:
```lua
-- Inside the loose Lua script
local somemathfunction=memoize(math.somemathfunction)
```
  - Plus, `math.somemathfunction` itself, when called, is __not__ memoized
2. After redis-evaluating a loose Lua script, when I memoize a __local__ function like this:
```lua
-- Inside the loose Lua script
function somelocalfunction(...) return someotherlocalfunction(...) end
local somelocalfunction=memoize(somelocalfunction)
```

**Comment by kikito** [comment]
> 1. After redis-evaluating a loose Lua script, when I memoize a global function [...]
> 2. After redis-evaluating a loose Lua script, when I memoize a local function like this [...]

Yes, in both cases as long as `somemathfunction` and `somelocalfunction` don't "survive" (i.e. they are not assigned to some global) the memory dedicated to their caches will be released. And non-memoized functions should not be affected.

Thanks for testing this, and for helping me improve the library. I'm closing this issue now.

**Comment by tw-bert** [comment]
@kikito Great.

Sidenote: Before trying your solution, I tried several other more trivial solutions (and the more complex [multikey](https://github.com/siffiejoe/lua-multikey/blob/master/src/multikey/memoize.lua) one), but they all had issues for our use cases. Thank you for OSS-ing this.
